09-06 16:22:37 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Function GEOTOOLSVERSION not found; SQL statement:
SELECT GeoToolsVersion() [90022-104]
	at org.h2.message.Message.getSQLException(Message.java:103)
	at org.h2.message.Message.getSQLException(Message.java:114)
	at org.h2.message.Message.getSQLException(Message.java:77)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1906)
	at org.h2.command.Parser.readFunction(Parser.java:1947)
	at org.h2.command.Parser.readTerm(Parser.java:2221)
	at org.h2.command.Parser.readFactor(Parser.java:1835)
	at org.h2.command.Parser.readSum(Parser.java:1822)
	at org.h2.command.Parser.readConcat(Parser.java:1795)
	at org.h2.command.Parser.readCondition(Parser.java:1668)
	at org.h2.command.Parser.readAnd(Parser.java:1648)
	at org.h2.command.Parser.readExpression(Parser.java:1640)
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:1555)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1585)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1490)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1335)
	at org.h2.command.Parser.parseSelect(Parser.java:1323)
	at org.h2.command.Parser.parsePrepared(Parser.java:392)
	at org.h2.command.Parser.parse(Parser.java:288)
	at org.h2.command.Parser.parse(Parser.java:260)
	at org.h2.command.Parser.prepareCommand(Parser.java:232)
	at org.h2.engine.Session.prepareLocal(Session.java:352)
	at org.h2.engine.Session.prepareCommand(Session.java:313)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1043)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:151)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.geotools.data.h2.H2Dialect.initializeConnection(H2Dialect.java:98)
	at org.geotools.data.h2.H2DialectBasic.initializeConnection(H2DialectBasic.java:56)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1247)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.getTypeNames(ContentDataStore.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyBeanProperty._doget(PyBeanProperty.java:32)
	at org.python.core.PyObject._doget(PyObject.java:1078)
	at org.python.core.PyObject.__get__(PyObject.java:3676)
	at org.python.core.PyObject.object___findattr__(PyObject.java:3706)
	at org.python.core.PyObject.object___getattribute__(PyObject.java:3692)
	at org.python.core.PyObject$object___getattribute___exposer.__call__(Unknown Source)
	at org.python.core.PyObjectDerived.__findattr_ex__(PyObjectDerived.java:993)
	at org.python.core.PyObject.__getattr__(PyObject.java:929)
	at geoscript.workspace.workspace$py.layers$3(geoscript/workspace/workspace.py:36)
	at geoscript.workspace.workspace$py.call_function(geoscript/workspace/workspace.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at geoscript.workspace.workspace$py.layer$4(geoscript/workspace/workspace.py:58)
	at geoscript.workspace.workspace$py.call_function(geoscript/workspace/workspace.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.workspace.workspace$py.addLayer$6(geoscript/workspace/workspace.py:100)
	at geoscript.workspace.workspace$py.call_function(geoscript/workspace/workspace.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx5.f$0(<stdin>:1)
	at org.python.pycode._pyx5.call_function(<stdin>)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.core.Py.exec(Py.java:1236)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:147)
	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:89)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:70)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:46)
	at org.python.util.InteractiveConsole.push(InteractiveConsole.java:110)
	at org.python.util.InteractiveConsole.interact(InteractiveConsole.java:90)
	at org.python.util.jython.run(jython.java:299)
	at org.python.util.jython.main(jython.java:117)
09-06 16:29:30 jdbc[8]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.core.Py.exec(Py.java:1236)
	at org.python.pycode._pyx0.f$0(run.py:23)
	at org.python.pycode._pyx0.call_function(run.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-06 16:29:30 jdbc[6]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.core.Py.exec(Py.java:1236)
	at org.python.pycode._pyx0.f$0(run.py:23)
	at org.python.pycode._pyx0.call_function(run.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-06 16:29:30 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.core.Py.exec(Py.java:1236)
	at org.python.pycode._pyx0.f$0(run.py:23)
	at org.python.pycode._pyx0.call_function(run.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-06 16:29:30 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx2.f$0(<string>:1)
	at org.python.pycode._pyx2.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.core.Py.exec(Py.java:1236)
	at org.python.pycode._pyx0.f$0(run.py:23)
	at org.python.pycode._pyx0.call_function(run.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:37:50 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:37:50 jdbc[8]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:37:50 jdbc[6]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:37:50 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:38:53 jdbc[8]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:38:53 jdbc[6]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:38:53 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:38:53 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
09-07 15:47:06 jdbc[8]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:47:06 jdbc[6]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:47:06 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 15:47:06 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 16:04:33 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 16:04:33 jdbc[8]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 16:04:33 jdbc[6]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
09-07 16:04:33 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:54)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:294)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:840)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:96)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:880)
	at org.geotools.jdbc.JDBCDataStore.createConnection(JDBCDataStore.java:1242)
	at org.geotools.jdbc.JDBCDataStore.createTypeNames(JDBCDataStore.java:672)
	at org.geotools.data.store.ContentDataStore.entry(ContentDataStore.java:523)
	at org.geotools.data.store.ContentDataStore.ensureEntry(ContentDataStore.java:554)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:347)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:314)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:175)
	at org.python.core.PyObject.__call__(PyObject.java:355)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at geoscript.layer.h2$py.__init__$2(../geoscript/layer/h2.py:17)
	at geoscript.layer.h2$py.call_function(../geoscript/layer/h2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyFunction.__call__(PyFunction.java:380)
	at org.python.core.PyInstance.__init__(PyInstance.java:120)
	at org.python.core.PyClass.__call__(PyClass.java:194)
	at org.python.core.PyObject.__call__(PyObject.java:414)
	at org.python.core.PyObject.__call__(PyObject.java:418)
	at layer.h2test$py.setUp$2(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py:8)
	at layer.h2test$py.call_function(/Users/jdeolive/Devel/geoscript-py/tests/layer/h2test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:381)
	at org.python.core.PyObject.__call__(PyObject.java:385)
	at unittest$py.run$26(/opt/jython-2.5rc2/Lib/unittest.py:278)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$27(/opt/jython-2.5rc2/Lib/unittest.py:281)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$45(/opt/jython-2.5rc2/Lib/unittest.py:434)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject._callextra(PyObject.java:537)
	at unittest$py.__call__$46(/opt/jython-2.5rc2/Lib/unittest.py:437)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObjectDerived.__call__(PyObjectDerived.java:975)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at unittest$py.run$84(/opt/jython-2.5rc2/Lib/unittest.py:725)
	at unittest$py.call_function(/opt/jython-2.5rc2/Lib/unittest.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:297)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:191)
	at org.python.core.PyFunction.__call__(PyFunction.java:385)
	at org.python.core.PyMethod.__call__(PyMethod.java:215)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:221)
	at org.python.core.PyMethod.__call__(PyMethod.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:397)
	at org.python.core.PyObject.__call__(PyObject.java:401)
	at org.python.pycode._pyx0.f$0(all.py:29)
	at org.python.pycode._pyx0.call_function(all.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1192)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:166)
	at org.python.util.jython.run(jython.java:229)
	at org.python.util.jython.main(jython.java:117)
